global using System.Collections.Frozen;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Globalization;
global using System.Net.Http;
global using System.Runtime.InteropServices;
global using System.Runtime.Versioning;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using System.Threading.Tasks;
global using UniSentinel.Config;
global using UniSentinel.Core;
global using UniSentinel.Handlers;
global using UniSentinel.Handlers.CSharp;
global using Microsoft.Extensions.DependencyInjection;
global using UniSentinel.Core.Commands;
global using UniSentinel.Core.Config;

