name: Build and Release Uni-Sentinel

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            rid: linux-x64
            asset_name: uni-sentinel-linux

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Install Native AOT dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y clang zlib1g-dev

    - name: Publish (Native AOT)
      run: dotnet publish ./UniSentinel.csproj -c Release -r ${{ matrix.rid }} --self-contained true -o ./publish /p:PublishAot=true

    - name: Rename & Prepare
      shell: bash
      run: |
        mv ./publish/UniSentinel ./${{ matrix.asset_name }}

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.asset_name }}

  create_release:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v3.0.${{ github.run_number }}
          name: Uni-Sentinel v3.0.${{ github.run_number }}
          files: |
            uni-sentinel-linux/uni-sentinel-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
